# -*- coding: utf-8 -*-
"""math_and_stats

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kABDff3JICbbdz0dwMhJ11xQQqqSK4-Y
"""

import random
import math
import statistics

vals_1_100 = range(1,100)
vals_sample = random.sample(vals_1_100, 75)
vals_choices = random.choices(vals_1_100, k = 200)
radius = random.randint(3,10)
pi = math.pi

"""# _Experimenting with a subset of integers 1-100"""

sample_sum = sum(vals_sample)
sample_avg = statistics.mean(vals_sample)
sample_median = statistics.median(vals_sample)

"""# _Experimenting with a superset of 200 values, integers 1-100"""

avg_200 = statistics.mean(vals_choices)
median_200 = statistics.median(vals_choices)
mode_200 = statistics.mode(vals_choices)
deviation_200 = statistics.stdev(vals_choices)
variance_200 = statistics.variance(vals_choices)

"""# _Modeling a random circle"""

area = pi * radius ** 2
area_rounded_up = math.ceil(area)
area_rounded_down = math.floor(area)

"""# Output"""

print('_Experimenting with a subset of integers 1-100:')
print(f'Sum of 75 sample values from 1-100: {sample_sum}')
print(f'Average of 75 sample values: {sample_avg}')
print(f'Median of 75 sample values: {sample_median}')
print(f'\n')
print('_Experimenting with a superset of 200 values, integers 1-100:')
print(f'Average of 200 values: {avg_200}')
print(f'Median of 200 values: {median_200}')
print(f'Mode of 200 values: {mode_200}')
print(f'Standard deviation of 200 values: {deviation_200}')
print(f'Variance of 200 values: {variance_200}')
print('\n')
print('_Modeling a random circle:')
print(f'Radius = {radius}, area = {area_rounded_up} rounded up to the nearest integer')
print(f'Radius = {radius}, area = {area_rounded_down} rounded down the nearest integer')