# -*- coding: utf-8 -*-
"""sampling_tools

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwyYe12jUnITa05m5dDbtbOT5ssRWsLM
"""

import random

products = ['Laptop', 'Monitor', 'Keyboard', 'Mouse', 'Webcam', 'Headset', 'Docking Station', 'USB Hub', 'Desk Lamp', 'Surge Protector']
#Product of the Day:
print(random.choice(products))

print(random.sample(products, k=3))

random.shuffle(products)
print(products)

random.randint(50,300)